### ISSUE TITLE
Add node_modules to .gitignore

### ISSUE THREAD

**Issue by dakaza98** [MaikePaetzel/1md034_students#2]
I noticed that this project does not have a .gitignore. It should have one with an ignore rule for node_modules/ so that students don't to commit all their node modules.

**Comment by foting** [comment]
Good point! The 2020 version of the lab instructions has a more thorough introduction to git where creating a .gitignore file and adding node_modules/ is included as a task. So solving this is left as a learning experience to the student ;-)
